/**
 * <p>This package is designed for programs that read the Famitracker music interface.
 * This now supports reading files with .ftm suffix, as well as txt files generated by Famitracker.
 *
 * <p>Famitracker supports exporting txt files since version 0.4.
 * Since this type of text file is easy to read, it is selected as the reading file format.
 * </p>
 *
 * @author Zdream
 * @date 2017-12-03
 */

package zdream.nsfplayer.ftm;